Array Creations

Creating arrays from python lists
- 1D array (data only in rows)
- 2D array or matrix (data in rows & columns)
- Multidimensional array (3D,4D,5D...)

In [2]:
import numpy as np
arr_1d=np.array([12,3,45,7,14])
print(arr_1d)

[12  3 45  7 14]


In [3]:
arr_2d=np.array([[1,2,3],[5,3,2],[11,32,40]])
print(arr_2d)

[[ 1  2  3]
 [ 5  3  2]
 [11 32 40]]


Creating array with default values
- using built-in function np.zeros(shape), shape is the size of array
- to replace default values in future
- np.zeros(shape) set the default values to 0
- np.ones(shape) set the default values to 1
- np.full(shape,value) set the default values what we want

In [15]:
arr_zeroes=np.zeros(5)
print(arr_zeroes)

[0. 0. 0. 0. 0.]


In [16]:
arr_ones=np.ones(5)
print(arr_ones)

[1. 1. 1. 1. 1.]


In [17]:
arr_ful=np.full((3,3),2)
print(arr_ful)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


Creating sequence of numbers in numpy
- use arange(start,stop,step)
- stop is not included

In [18]:
arr_seq=np.arange(0,21,2)
print(arr_seq)

[ 0  2  4  6  8 10 12 14 16 18 20]


Creating identity matrix
- use eye(size)

In [20]:
id_mtrx=np.eye(2)
print(id_mtrx)

[[1. 0.]
 [0. 1.]]


Array Operations
- shape, gives rows & columns
- size, gives no. of elements
- ndim, gives no. of dimensions
- dtype, gives data type 
- astype, type conversion

In [22]:
arr1=np.array([[2,3,1],[1,2,4]])
print(arr1.shape)
print(arr1.size)

(2, 3)
6


In [16]:
a_1d=np.array([2,3,1])
a_2d=np.array([[12,4,11],[0,0,1]])
a_3d=np.array([[[1,40,11],[0,0,1],[2,2,1],[11,23,44]]])
print(a_1d.ndim)
print(a_2d.ndim)
print(a_3d.ndim)
print(a_1d.dtype)

1
2
3
int64


In [25]:
arr_old=np.array([3.4,5.5,1.1])
print(arr_old.dtype)
arr_new=arr_old.astype(int)
print(arr_new)
print(arr_new.dtype)

float64
[3 5 1]
int64


Arithmetic operations on array

In [26]:
print(arr_1d+5)
print(arr_1d-2)
print(arr_1d*3)
print(arr_1d**2)
print(arr_1d/8)
print(arr_1d%10)


[17  8 50 12 19]
[10  1 43  5 12]
[ 36   9 135  21  42]
[ 144    9 2025   49  196]
[1.5   0.375 5.625 0.875 1.75 ]
[2 3 5 7 4]


Aggregation functions
- np.sum()
- np.mean()
- np.std()
- np.var()
- np.min()
- np.max()

In [27]:
print(np.sum(a_2d))
print(np.mean(a_2d))
print(np.std(a_2d))
print(np.var(a_2d))
print(np.min(a_2d))
print(np.max(a_2d))

28
4.666666666666667
5.022173057773122
25.222222222222225
0
12


Indexing & Slicing
- arr[index], for 1D array
- arr[rows,columns], for 2D array
- arr[start:stop:step], stop is excluded
- fancy indexing, selecting multiple elements at once using indices as list

In [ ]:
print(arr_1d[3])
print(arr_1d[::-1])
print(arr_1d[2:5:1])
print(arr_1d[[0,3,4]])#fancy indexing
print(arr_1d[arr_1d<15])#boolean masking or filtering

7
[14  7 45  3 12]
[45  7 14]
[12  7 14]
[12  3  7 14]


Reshaping, changing array dimension(shape) without modifying data
- reshape(rows,columns), if dimensions match

In [14]:
a=np.array([2,3,4,1])
arr_change=a.reshape(2,2)
print(arr_change)

[[2 3]
 [4 1]]


Flattening array
- ravel(), view
- flatten(), copy

In [37]:
a2=np.array([[1,23,44],[12,30,5]])
print(a2.ravel())
print(a2.flatten())

[ 1 23 44 12 30  5]
[ 1 23 44 12 30  5]


Array Modifications
- np.insert(array,index,value,axis=None),axis=0 row-wise & 1 column-wise,by     default row-wise
- np.append(array,value), insert the element at the end
- np.concatenate(arrays,axis), combine two arrays
- np.delete(array,index,axis), remove the element

In [26]:
#1D array
ar=np.insert(arr_1d,2,0,None)
print(ar)

#2D array
ar2=np.insert(arr_2d,1,[2,0,9],1)
print(ar2)

ar_apnd=np.append(arr_1d,11)
print(ar_apnd)
ar_concat=np.concatenate((a_1d,a))
print(ar_concat)
ar_remove=np.delete(arr_1d,3)
print(ar_remove)
ar_rmv=np.delete(arr_2d,2,0)
print(ar_rmv)

[12  3  0 45  7 14]
[[ 1  2  2  3]
 [ 5  0  3  2]
 [11  9 32 40]]
[12  3 45  7 14 11]
[2 3 1 2 3 4 1]
[12  3 45 14]
[[1 2 3]
 [5 3 2]]


Stacking, combine multiple arrays
- np.vstack(), row-wise
- np.hstack(), column-wise

Splitting, divide array into sub-arrays
- np.split(), split in equal parts
- np.vsplit(), split vertically
- np.hsplit(), split horizontally

In [37]:
A1=np.array([1,2,3])
A2=np.array([4,5,6])
print(np.vstack((A1,A2)))
print(np.hstack((A1,A2)))

print(np.split(A1,1))
print(np.hsplit(A1,1))
print(np.vsplit(arr_2d,3))
print(np.hsplit(arr_2d,3))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[array([1, 2, 3])]
[array([1, 2, 3])]
[array([[1, 2, 3]]), array([[5, 3, 2]]), array([[11, 32, 40]])]
[array([[ 1],
       [ 5],
       [11]]), array([[ 2],
       [ 3],
       [32]]), array([[ 3],
       [ 2],
       [40]])]


Broadcasting

In [41]:
Arr1=np.array([2,4,1])
print(Arr1+arr_2d)#equal dimension
Arr=np.array([10])
print(Arr+arr_2d)#single element
Arr2=np.array([2,3])
#print(Arr2+a_2d)#incompatible shape, error

[[ 3  6  4]
 [ 7  7  3]
 [13 36 41]]
[[11 12 13]
 [15 13 12]
 [21 42 50]]


In [46]:
arr_0 = np.array([[10, 20],
                [30, 40]])

print(arr_0 + [1, 2])#1D column-wise addition
print(arr_0+ [[1], [2]])#2D row-wise addition

arr_z = np.array([[1,2,3],
                [4,5,6]])

print(arr_z + [1,2,3])    
print(arr_z + [[1],[2]])    
print(arr_z + [1])        



[[11 22]
 [31 42]]
[[11 21]
 [32 42]]
[[2 4 6]
 [5 7 9]]
[[2 3 4]
 [6 7 8]]
[[2 3 4]
 [5 6 7]]


Vectorization

In [49]:
result=A1+A2
print(result)
print(arr_1d*2)

[5 7 9]
[24  6 90 14 28]


Handling missing values
- np.isnan(), detect missing values
- np.nan_to_num(arr,nan=value), replace missing values with other values 
- np.isinf(), detect infinite values

In [ ]:
a_0=np.array([21,33,np.nan,11,np.nan,44])#nan stands for not a number
print(np.isnan(a_0))
print(np.nan==np.nan)#can't compare direct
print(np.nan_to_num(a_0))#replace with default value 0
print(np.nan_to_num(a_0,nan=5))

a_1=np.array([1,4,5,np.inf,0,-np.inf])
print(np.isinf(a_1))
print(np.nan_to_num(a_1,posinf=1000,neginf=-1000))#replace values


[False False  True False  True False]
False
[21. 33.  0. 11.  0. 44.]
[21. 33.  5. 11.  5. 44.]
[False False False  True False  True]
[    1.     4.     5.  1000.     0. -1000.]
