In [ ]:
import numpy as np
zeroes=np.zeros(10)
print(zeroes)
vowels=np.array(['a','e','i','o','u'])
print(vowels)
ones_2d=np.ones((2,5),dtype=int)
print(ones_2d)
myarray1=np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
print(myarray1)
myarray2=np.arange(4,61,4,dtype=float).reshape(3,5)
print(myarray2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
['a' 'e' 'i' 'o' 'u']
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[  2.7  -2.  -19. ]
 [  0.    3.4  99.9]
 [ 10.6   0.   13. ]]
[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


In [ ]:
print("dimension:",zeroes.ndim,"shape:",zeroes.shape,"size:",zeroes.size,"data type:",zeroes.dtype,"itemsize:",zeroes.itemsize)
print("dimension:",vowels.ndim,"shape:",vowels.shape,"size:",vowels.size,"data type:",vowels.dtype,"itemsize:",vowels.itemsize)
print("dimension:",ones_2d.ndim,"shape:",ones_2d.shape,"size:",ones_2d.size,"data type:",ones_2d.dtype,"itemsize:",ones_2d.itemsize)
print("dimension:",myarray1.ndim,"shape:",myarray1.shape,"size:",myarray1.size,"data type:",myarray1.dtype,"itemsize:",myarray1.itemsize)
print("dimension:",myarray2.ndim,"shape:",myarray2.shape,"size:",myarray2.size,"data type:",myarray2.dtype,"itemsize:",myarray2.itemsize)

ones_new=ones_2d.reshape(1,10)
print(ones_new)
print(vowels[[1,2]])
print(myarray1[1:3,])
print(myarray1[:,0:2])
print(myarray1[1:3, 0])
print(vowels[::-1])


dimension: 1 shape: (10,) size: 10 data type: float64 itemsize: 8
dimension: 1 shape: (5,) size: 5 data type: <U1 itemsize: 4
dimension: 2 shape: (2, 5) size: 10 data type: int64 itemsize: 8
dimension: 2 shape: (3, 3) size: 9 data type: float64 itemsize: 8
dimension: 2 shape: (3, 5) size: 15 data type: float64 itemsize: 8
[[1 1 1 1 1 1 1 1 1 1]]
['e' 'i']
[[ 0.   3.4 99.9]
 [10.6  0.  13. ]]
[[ 2.7 -2. ]
 [ 0.   3.4]
 [10.6  0. ]]
[ 0.  10.6]
['u' 'o' 'i' 'e' 'a']


In [ ]:
print(ones_2d/3)
print((myarray1**3)/2)
result=np.sqrt(myarray2)/2
print(np.round(result,2))#result 2 place decimal
myarray3=myarray1@myarray2#matrix multiplication
print(myarray3)
#myarray1(3,3) and myarray2(3,5)
#Due to incompatible shapes element-wise operation can't perform 
#print(myarray1/myarray2)
#print(myarray1*myarray2)
#print(myarray1+myarray2)
#print(myarray2-myarray1)


[[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]]
[[ 9.841500e+00 -4.000000e+00 -3.429500e+03]
 [ 0.000000e+00  1.965200e+01  4.985015e+05]
 [ 5.955080e+02  0.000000e+00  1.098500e+03]]
[[1.   1.41 1.73 2.   2.24]
 [2.45 2.65 2.83 3.   3.16]
 [3.32 3.46 3.61 3.74 3.87]]
[[ -873.2  -946.4 -1019.6 -1092.8 -1166. ]
 [ 4477.2  4890.4  5303.6  5716.8  6130. ]
 [  614.4   708.8   803.2   897.6   992. ]]


In [ ]:
print(ones_2d.transpose())#change rows into columns
print(myarray2.transpose())
sorted=np.sort(vowels)
print(sorted[::-1])#reverse order
sorted2=np.sort(myarray1,axis=0)#column-wise sorted
print(sorted2)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
[[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]
['u' 'o' 'i' 'e' 'a']
[[  0.   -2.  -19. ]
 [  2.7   0.   13. ]
 [ 10.6   3.4  99.9]]


In [ ]:
myarray2A,myarray2B,myarray2C,myarray2D,myarray2E=np.hsplit(myarray2,5)#horizontal split
myarray2A,myarray2B,myarray2C,myarray2D,myarray2E=np.split(myarray2,5,axis=1)#axis=1 ->column-wise
print(myarray2A,myarray2B,myarray2C,myarray2D,myarray2E)

zeroesA,zeroesB,zeroesC,zeroesD=np.split(zeroes,[2,5,7])
print(zeroesA,zeroesB,zeroesC,zeroesD)

arr=np.concatenate((myarray2A,myarray2B,myarray2C),axis=1)
print(arr)

[[ 4.]
 [24.]
 [44.]] [[ 8.]
 [28.]
 [48.]] [[12.]
 [32.]
 [52.]] [[16.]
 [36.]
 [56.]] [[20.]
 [40.]
 [60.]]
[0. 0.] [0. 0. 0.] [0. 0.] [0. 0. 0.]
[[ 4.  8. 12.]
 [24. 28. 32.]
 [44. 48. 52.]]


In [ ]:
myarray4=np.arange(-1,9.5,0.25).reshape(14,3)
print(myarray4)
a1,a2,a3=np.array_split(myarray4,3,axis=0)#array_split(), works even when division is not exact
print(a1,a2,a3)

[[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]]
[[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]] [[2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]
 [5.   5.25 5.5 ]
 [5.75 6.   6.25]] [[6.5  6.75 7.  ]
 [7.25 7.5  7.75]
 [8.   8.25 8.5 ]
 [8.75 9.   9.25]]


In [ ]:
res=np.sum(myarray1)
print(res)
res2=np.sum(myarray1,axis=1)#row-wise elements sum
print(res2)


108.60000000000001
[-18.3 103.3  23.6]
